name: chain_of_trust
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  flutter_dash: ^1.0.0
  intl: ^0.18.1

  # Firebase Dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.0.0

  # Image & File Picker
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  # Hashing and QR Tools
  crypto: ^3.0.5
  qr_code_tools: ^0.2.0
  mobile_scanner: ^3.5.0
  qr_flutter: ^4.1.0

  # HTTP & State Management
  http: ^1.2.2
  provider: ^6.1.2

  # For saving files and handling permissions
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/fingerprint_icon.png
    - assets/logo.jpg
    - assets/salman.jpg
